[package]
name = "helper"
version = "0.1.0"
edition = "2024"

[features]
default = []
qemu = [
    "dep:libafl",
    "dep:libafl_bolts",
    "dep:libafl_qemu",
    "dep:libafl_targets",
]

[dependencies]
common = { path = "../common" }
host_harness = { path = "../host_harness" }
clap = { version = "4.5", features = ["derive"] }
libafl = { version = "0.15.1", optional = true }
libafl_bolts = { version = "0.15.1", optional = true }
libafl_qemu = { version = "0.15.1", features = [
    "riscv64",
    "systemmode",
], default-features = false, optional = true }
libafl_targets = { version = "0.15.1", optional = true }
walkdir = "2.5.0"
regex = "1.11.1"
tempfile = "3.17.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
toml = "0.8.20"

[build-dependencies]
libafl_qemu_build = "0.15.1"
